### ISSUE TITLE
Keyboard disabled on Update

### ISSUE THREAD

**Issue by jag3773** [Door43/translationKeyboard#15]
If you install tK from the app store, enable it as an input method, then install beta4, tK is no longer enabled as an input method, you have to go back through the enable step.  This happens even if tK is the currently selected input method.

**Comment by bknatterud** [comment]
A quick update on this issue....
it looks like it's changing the internal paths from "org.distantshoresmedia.translationkeyboard-1.apk" to "org.distantshoresmedia.translationkeyboard-2.apk" possibly a versioning difference.
We trying to determine if a fix for this is possible right now. It will probably be later today before we know if there is a fix for this.
It's happening because we changed the name of the input method.

**Comment by bknatterud** [comment]
We have possibly fixed this issue i beta5.

**Comment by bknatterud** [comment]
Ok. Here is what we found on this...
We were not ever able to find any conclusive answer as to why it happens or exactly what causes it.
Our best guess is it's either a bug in android in the file system, or a security feature due to a version jump or new required permissions (network access).
We can keep looking if you like.
